sudo: required

language: generic

service:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -f Dockerfile.dev -t blueraint/docker-react-app  ./

script:
  - docker run -e CI=true blueraint/docker-react-app npm run test -- --coverage

# AWS deploy info(using elastic-beanstalk)
deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react-app-sample"
  env: "Dockerreactappsample-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-971433154392"
  bucket_path: "docker-react-app-sample"
  on:
    branch: master

# AWS 연동시 api-key (access-key 및 secret-key)는 노출되지 않아야 하므로 여기서는 travis -> options -> settings -> env variables에 세팅하여 이용한다 
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_ACCESS_KEY 